sudo: required

services:
  - docker

script:
  - make image
  # We set these via the Travis CI website.
  - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin
  - make push
